stages:
  - analyze


analyze:sonar:
  stage: analyze
  image: 
    name: docker:dind
  services:
    - maven:3-openjdk-8
    - sonarsource/sonar-scanner-cli:4.5 
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Shallow cloning needs to be disabled.
    # See https://docs.sonarqube.org/latest/analysis/gitlab-cicd/.
    DOCKER_TLS_CERTDIR: ""
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn deploy
    - sonar-scanner
  rules:
    # SonarQube CommunityEdition only supports analyzing a single branch.
    # So only run on main.
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - when: never




