---
- name: Installation de hello
  hosts: local
  tasks:
    - name: Start maven container
      docker_container:
        name: 'maven'
        image: maven:3.6.3-jdk-11
        state: 'started'
      register : result
    
